name: "CI"

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-16.04

    steps:

    - uses: actions/checkout@v1
    
    - name: Install Dependencies and get source code
      run: |
        sudo apt-get update -qq
        sudo add-apt-repository ppa:beineri/opt-qt-5.10.1-xenial -y
        sudo apt-get -y install qt510base qt510x11extras
        source /opt/qt*/bin/qt*-env.sh
        
    - name: Build
      run: |
        mkdir build && cd build/
        qmake CONFIG+=release PREFIX=/usr ..
        make -j$(nproc)
        # make INSTALL_ROOT=appdir -j$(nproc) install ; find appdir/
        mkdir -p appdir/usr/bin
        cp dvkbuntu-easy-menu-qt appdir/usr/bin # FIXME: 'make install' should do this
        mkdir -p appdir/usr/share/applications # FIXME: 'make install' should do this
        cp dvkbuntu-easy-menu-qt.desktop appdir/usr/share/applications # FIXME: 'make install' should do this
        mkdir -p appdir/usr/share/icons/hicolor/256x256/apps/ # FIXME: 'make install' should do this
        cp ../Images/dvkbuntu-easy-menu-qt.png appdir/usr/share/icons/hicolor/128x128/apps/ # FIXME: 'make install' should do this
        cp appdir/usr/share/icons/hicolor/256x256/apps/dvkbuntu-easy-menu-qt.png appdir/
        find appdir/
        
    - name: Generate AppImage
      run: |
        APPDIR=$(readlink -f appdir) # Why is this needed?
        wget -c -q https://github.com/$(wget -q https://github.com/probonopd/go-appimage/releases -O - | grep "appimagetool-.*-x86_64.AppImage" | head -n 1 | cut -d '"' -f 2)
        chmod +x appimagetool-*.AppImage
        ./appimagetool-*.AppImage deploy "$APPDIR"/usr/share/applications/*.desktop --appimage-extract-and-run # Bundle EVERYTHING
        ./appimagetool-*.AppImage "$APPDIR" --appimage-extract-and-run # turn AppDir into AppImage
        
    - name: Release AppImage
      uses: marvinpinto/action-automatic-releases@latest
      with:
        title: AppImage
        automatic_release_tag: continuous
        prerelease: true
        draft: false
        files: |
          D*.AppImage*
        repo_token: ${{ secrets.GITHUB_TOKEN }}
